### ISSUE TITLE
Update $save to work with ObjectIds

### ISSUE THREAD

**Issue by jde** [coralproject/shelf#155]
The $save xenia decorator allows us to pass individual or arrays of values from past queries to future queries.  

It works for all types that are automatically inferred by mongo.  This does not work for the ObjectId type, which must be explicitly taken from string to ObjectId.

Update the $save internals to work with bson.ObjectId typed vars.

**Comment by jde** [comment]
It looks like the bson type is stripped due it it's being stored as an interface{} and not being reasserted when read here:

https://github.com/coralproject/xenia/blob/master/internal/exec/variables.go#L284

**Comment by jde** [comment]
I came up with this fix, but it would introduce baffling behavior...

```
	// Reintroduce ObjectIds. This process may be too greedy causing all values of
	//  12 bytes length to be interpreted as Ids. This trade-off is temporarily acceptible
	//  since passing ObjectIds is the primary use case and will account for the
	//  vast majority of data $save'd
	for k, v := range data {
		if len(v) == 12 {
			data[k] = bson.ObjectId(v)
		}
	}
```

thoughts?

**Comment by ardan-bkennedy** [comment]
That fix can't be used. We can inspect the type of value inside the interface{}. Let me take a look.

**Comment by ardan-bkennedy** [comment]
I believe this is working and we have tests.
