### ISSUE TITLE
SPIKE: Set standard for logging

### ISSUE THREAD

**Issue by jde** [coralproject/shelf#156]
Discussion toward a standard logging for all Coral Go code.

Requirements:

- structured logging
- integration with a variety of visualization/searching services
- good formatting on output (columns, colors, etc...)

**Comment by ardan-bkennedy** [comment]
If we are going to rip out the current logger and move to structured logging the we should use log15 from go-kit. 

We also need to talk about what is logged and when. Logging is a primative component. This will require a decent effort. I just wonder what we are looking to achieve that metrics currently can't give us?
