### ISSUE TITLE
SPIKE: define error standards

### ISSUE THREAD

**Issue by jde** [coralproject/shelf#157]
Come up with standards for logging across all Go apps.

**Comment by jde** [comment]
http://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully 

The source is disreputable, but the ideas are solid. :)

**Comment by ardan-bkennedy** [comment]
We must talk about this. This is more a philosophy than a technical issue. I like some things this package is doing and not others. I have some of my own ideas. These ideas change depending where the code lives.
