### ISSUE TITLE
SPIKE: How can we share routes and handlers between apps?

### ISSUE THREAD

**Issue by jde** [coralproject/shelf#162]
Coral requires us to be able to deliver solutions to large and small customers. We will have (at least) 3 distinct products.

The ability to build programs with different combinations of routes will help us achieve this.

For example, for a small, simple install I would like to package xenia, sponge and shelf functionality into a single binary.  The packages are already compossible but the routes live explicitly under the apps, so they are not.

Proposal:

Create a top level `/api/` folder with sub-packages.  Each sub-package contains routes and handlers for a group of functionality.  Web apps can be passed into a "register" func that will enable these endpoints during the app startup.

**Comment by jde** [comment]
Initial route groupings:

* ask - (custom routes for forms, form_submissions and form_galleries)
* xenia - all the xenia routes
* sponge - dynamically created routes depending on type (and other) information
* shelf - (?)

**Comment by ardan-bkennedy** [comment]
I'm against building all the API's into a single binary thought is everything can be in the same project this is not a problem. We just need another package main that calls into the routes function of each services and everything gets built. 

But I believe you can still have separate services all running on the same instance and still have a system that is easy to deploy. 

Remember you have Mongo, Anvil and other services as well.
