### ISSUE TITLE
Move sponge packages (strategy, fiddler and source) into shelf

### ISSUE THREAD

**Issue by gabelula** [coralproject/shelf#191]
Strategy package in Sponge is the one in charge of the transformations that needs to happen to the data to get into our system. 

- [x] Move strategy package into shelf
- [x] Move fiddler package into shelf
- [ ] Move source package into shelf
- [ ] Get cmd sponge working in shelf

Next steps:

- Convert configuration file into a mongodb collection
- Discuss how to use it for setting up the relationships in the views

**Comment by gabelula** [comment]
Pull Request https://github.com/coralproject/shelf/pull/193 , work in progress (do not merge).

**Comment by kgardnr** [comment]
Closing as the associated PR was closed.
