### ISSUE TITLE
Sponge, integrate item field requirement code when an item is posted into the system

### ISSUE THREAD

**Issue by jde** [coralproject/shelf#199]
This branch contains unreviewed, unintegrated code along with an orphaned test branch that ensures that items aren't duplicated when inserted.  It also contains a type system configuration that we should integrate into our universal configuration.

Integrate this code into the item upload process.

https://github.com/coralproject/shelf/tree/sponge-foreign-keys

**Comment by dwhitena** [comment]
This previous code is actually in the commit history, as it was merged in and then reverted.

**Comment by dwhitena** [comment]
The pattern, type, and relationship inference pieces are in place.  However, at some point we need to implement verification of required fields, needed for relationship inference.  Otherwise, there is a chance that junk data will be imported (although it won't make it into views).
