### ISSUE TITLE
CORS error when submitting forms

### ISSUE THREAD

**Issue by jde** [coralproject/shelf#204]
There's a cors error when submitting forms. 

To reproduce, 

1) go here: https://s3.amazonaws.com/nyt-stage/57c8719f95ae170007b5afff.html
2) fill out form
3) Click SUBMIT
4) open web console, see this error:

![screenshot 2016-09-09 09 54 35](https://cloud.githubusercontent.com/assets/259957/18389326/7c01504c-7673-11e6-8734-cc5964cd9d35.png)

We need to keep Access-Control-Origin at * or provide another way of letting people host these forms anywhere on the web.  This is not allowed "when the credentials flag is true."  

Can we safely set Access-Control-Allow-Credentials to false?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Credentials

**Comment by jde** [comment]
The headers are set here: https://github.com/coralproject/shelf/blob/master/vendor/github.com/ardanlabs/kit/web/app/app.go#L134

Access-Control-Allow-Credentials is not set.

It is unclear to me why this request alone triggers this behavior. All other api requests' headers are set here as well.

**Comment by wyattjoh** [comment]
I think it's related to the "credentials" flag being set in the javascript for the XHR request.

**Comment by jde** [comment]
You are correct.  Elkhorn is publishing forms with credentials headers.

Moving issue to: https://github.com/coralproject/elkhorn/issues/90
