### ISSUE TITLE
502 on form_galleries request

### ISSUE THREAD

**Issue by jde** [coralproject/shelf#205]
nginx returns a 502 on this request:
https://pillar_stg.coralproject.net/api/form_galleries/57c8719f95ae170007b5afff

It’s very interesting that this is an nginx reported 502.  It seems to indicate that Ask’d is not responding to this request at all.  This may point to a lack of response in a certain error state.

**Comment by wyattjoh** [comment]
Resolved in 34cb801c34d52bd2f1de8407d880260be93c9d60
