### ISSUE TITLE
Expose API endpoint that saves comment 

### ISSUE THREAD

**Issue by gabelula** [coralproject/shelf#222]
Creates an endpoint in the Corald service to save an item of type comment.

POST /v1/item

Parameter
{
  type: "comment",
  data: {}
}

Response Messages:

{
 "item_id: X
}

Story https://www.pivotaltracker.com/n/projects/1863625

**Comment by gabelula** [comment]
@davidgljay I want to confirm that you need item_id back in the response. We are not returning any ID in all other Upsert endpoints in the APIs we have.

**Comment by davidgljay** [comment]
Yes, I think that this makes sense unless there's a reason not to. It also
allows for consistency in how the frontend displays these items.
