### ISSUE TITLE
Deploy Corald into a staging server

### ISSUE THREAD

**Issue by gabelula** [coralproject/shelf#235]
We need to deploy corald to staging for the FE to start using it. The app is in this repository at cmd/corald. The environment variables in config/localhost.cfg are the ones that are needed for this.

**Comment by kgardnr** [comment]
@edefikh @jde @gabelula I think we should have a great discussion about the Talk architecture and how it will be deployed before we address this ticket. I will set up a meeting tomorrow.

**Comment by kgardnr** [comment]
Closing this as we will track the story in Pivotal
