### ISSUE TITLE
Embed references to related item ids by predicate in view items

### ISSUE THREAD

**Issue by jde** [coralproject/shelf#245]
Items in views need to contain references to related items in the view so that consumers can 'walk the graph'.

The references should be arrays of ids. The name of the array properties should be the _tag_ coming from the _view_ definition.

The following format was developed in conjunction with @davidgljay as optimized for fe consumption:

https://gist.github.com/jde/e64306c85b4345701cba33b2e786241a

Required for this user story:
https://www.pivotaltracker.com/story/show/130309739

**Comment by dwhitena** [comment]
See PR here: https://github.com/coralproject/shelf/pull/287
