### ISSUE TITLE
Get a single item and all related items

### ISSUE THREAD

**Issue by gabelula** [coralproject/shelf#250]
Get an item by item_id and all its related items.

Pivotal Tracker related Ticket: https://www.pivotaltracker.com/n/projects/1863625/stories/130310029

**Comment by jde** [comment]
My first thought is to create a new view that describes all of an item's relationships. The query would then return all records in that view for the given item.

**Comment by gabelula** [comment]
This is blocked by https://github.com/coralproject/shelf/issues/245
