### ISSUE TITLE
Corald: Create New Asset Item when a thread is put on a new page.

### ISSUE THREAD

**Issue by gabelula** [coralproject/shelf#251]
When a thread is embedded in a page, we will need to infer the Asset from the URL. The first time a new embed occurs, there’s a good chance that the Asset Item will not exist in the Item Store.

How do we infer an asset from a url?

Proposed solution:
On initial load of items in a stream
If the query comes back empty (not even the asset is returned)
Create a new Asset
Return the Asset 

Pivotal Tracker related ticket: https://www.pivotaltracker.com/story/show/130659649

**Comment by jde** [comment]
As per our sprint planning discussion, this issue is on hold. The linked ticket specifies one article, therefore article discovery by URL is not yet required. We will need this in the near future, however.
