### ISSUE TITLE
Track created and updated timestamps on sponged Upsert

### ISSUE THREAD

**Issue by jde** [coralproject/shelf#253]
It is traditionally the responsibility of the backend system to track create_date and update_date fields. Sponged should be no different.

For discussion, where / how should we store these fields in the item paradigm?

* we could store them in ``data.create_date`` and ``data.update_date``, but this may violate the do not touch the data principal
* we could create a new top level namespace: ``history.create_date`` && ``history.update_date```

I'm leaning toward the latter.  Having a history subdocument will allow us to track more event based item metadata in the future.

This feature is needed for this story, which is actively being developed:
https://www.pivotaltracker.com/story/show/130309941

**Comment by wyattjoh** [comment]
I've always been a fan of the `created_at` and `updated_at` timestamps on the item. I don't think that grouping the item into it's own subdocument adds much.

**Comment by gabelula** [comment]
I think it should be in the top leve as item.create_date and item.update_date. The item is the one being created or updated. What is the point of adding the history subdocument?

**Comment by jde** [comment]
+1 on the *_at naming convention.

The reason I thought history is that in the future we will want to track more finely detailed 'events'. This is, however, not a requirement now. It makes sense to keep these fields in the root.

Current proposal: ``item.created_at`` and ``item.updated_at``.
