### ISSUE TITLE
Implement actions in corald

### ISSUE THREAD

**Issue by jde** [coralproject/shelf#273]
Actions are defined here: https://github.com/coralproject/talk/blob/master/TERMINOLOGY.md

The first implementation of actions will:

- Be represented as an array named after the action of user_ids (actors) in the target item (comment)
- Arrays will be inferred from patterns (Blocked by #272)
- Actions must be in an _allowed actions_ list (we can hard code for now) aka, only flags and likes allowed.
- Users may only add one actions of a certain type to one item, aka, user_234 can only flag comment_885 once.

API suggestion:

POST     /v1/action/:actionType/item/:item_id
DELETE /v1/action/:actionType/item/:item_id

Known limitations:
- This will only store _that an action was taken_, no other data such as date_created will be initially supported. We have discussed storing additional action data either in parallel sub arrays of the target or in their own collection in the future.

**Comment by gabelula** [comment]
Related to https://github.com/coralproject/shelf/issues/252
