### ISSUE TITLE
Updatable page settings/config for pre/post moderation, steam depth, etc.

### ISSUE THREAD

**Issue by dwhitena** [coralproject/shelf#297]
At some point, administrators of the coral/talk system will want to turn on/off various pieces of functionality (e.g., pre/post moderation) for site-wide or per-page.  To enable this we need to have one or more page configs that state which of these levers/knobs have been turned on/off, such that the FE can make appropriate decisions when displaying a page.

To this end, we should explore/implement:
- page settings/config items that contain the information about how page setting/config was set up by an admin.  For example:
  
  ```
  {
           "type": "settings/config",
           "item_id": "....",
           "data": {
                       "moderation_type": "pre",
                       "child_depth": 5,
                      ....
          }
  }
  ```
- initialization of such a settings/config item.
- update of the settings/config.

**Comment by gabelula** [comment]
We should have configuration by page, section or site. And the page's configuration overwrites the section and site's ones.   

 https://github.com/coralproject/talk/blob/2c07ac63cf86715811fb1df31b217711674c3752/library/coral/Model.png

**Comment by dwhitena** [comment]
After thinking about this a bit and exploring some options, I think (at least to begin with) we don't need extra functionality for the initialization and update of `settings` items.  The admin FE can POST settings items to the normal sponge endpoint, which will upsert the item.

However, we will need
- a way to GET all the settings (or certain settings) on demand (which is basically a get by type), and 
- a way to return settings with views.  

Going to focus on these things.
